name: Node.js CI

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - .github/**
      - locales/**
      - sounds/**
      - package.json
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.11.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
